services:
  web3:
    build: apache
    ports:
      - 80:80
    volumes:
      - ./apache/test1.conf:/etc/apache2/sites-enabled/test1.conf
      - ./pablocn.lan:/opt/web/pablocn.lan
      # - ./doc:/app/doc
    networks:
      redeapache:
        aliases:
          - www.pablocn.lan
          - pablocn.lan
          - eq1.pablocn.lan

    develop:
      watch:
        - path: ./apache/test1.conf
          action: restart

  cliente:
    build: cliente
    hostname : cliente
    networks:
      - redeapache
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix


networks:
  redeapache:



